### ISSUE TITLE
A quick question on input range of tcnn.Encoding

### ISSUE THREAD

**Issue by GuangyuWang99** [alvaro-budria/NeuSacc#4]
Hi, thanks for this awesome implementation! I have a small question on the range of inputs to the tcnn encoding and network module in the sdf network. 

I think this implementation follows the convention in NeuS where the scene of interest is normalized within the bounding volume [-1, 1]^3. However, tiny-cuda-nn's encodings may all expect inputs within [0,1]^n by convention? And I haven't seen any squishing operation before feeding the input coordinates to the sdf network (just like what you do for the view-direction vectors in the color network).

Do we need to rescale the input range from [-1, 1] to [0, 1] before feeding into the tcnn encoding module?

Thanks in advance!

**Comment by alvaro-budria** [comment]
Hi, you're totally right about this, thanks for pointing it out. The encoding expects inputs to be in the [0, 1] range, and in fact performs a clamping to that range, so inputs outside that range are ignored.

I fixed this by appropriately scaling the input locations to the geometry network. It's in the `main` branch now.

Why did the system work despite the input range not being correct? My guess is that since the negative inputs do not have a corresponding gradient signal (due to the clamping), they are just ignored, and the network reconstructs the object with the positive values only. That means about half of the inputs were just ignored, and the center of the scene was placed not at (0,0,0) but somewhere around (0.5, 0.5, 0.5).
