### ISSUE TITLE
faster train

### ISSUE THREAD

**Issue by liusang** [alvaro-budria/NeuSacc#6]
Your work is great. Can you tell me how to set parameters to achieve significant acceleration? My own test is similar to the original neus speed

**Comment by fangchuan** [comment]
face the Same problem, it seems no acceleration with respect to original NeuS implementation, in the dtu_scan106 scene

**Comment by alvaro-budria** [comment]
Hi @fangchuan @liusang, I appreciate that you have taken the time to test the code.

First of all, it must be said that this implementation is quite unstable. If the parameters are changed a bit, the result can deteriorate quite a lot. However, that shouldn't be the problem here, as I used the default parameters to obtain the `dtu_scan06` rendering that you can see on the `ReadMe`.

In my case, the vanilla NeuS runs at about 4-6 iterations/s, whereas NeuSacc runs at about 20-25 iters/s. It takes about 30-45 min for NeuSacc to converge, while for NeuS after 45 min results are pretty decent but convergence is reached after 1.5-2 hours.

I am using an A100 GPU which is more optimized for FP16 operations compared to other GPUs. Maybe that could be the reason for the difference in performance.

That being said, if you are just looking for an accelerated NeuS that you can reliably run off-the-shelf, for the sake of your time I honestly recommend you take a look at [instant-nsr-pl](https://github.com/bennyguo/instant-nsr-pl). It's a more robust and more updated codebase that basically does much of what `NeuSacc` does to accelerate fitting of neural fields.
