### ISSUE TITLE
Result not good on custom data.

### ISSUE THREAD

**Issue by YiChenCityU** [alvaro-budria/NeuSacc#7]
Hi, did you test the code on the custom data processed by neus tutorial? I cannot get right mesh using this project. Thanks very much.

**Comment by alvaro-budria** [comment]
Hi @YiChenCityU, in my work I mostly deal with synthetic data, where I know ground truth camera matrices, so I have not tried running the code on custom data. Are you sure you are getting the right outputs from COLMAP? For instance, something I have encountered a few times is that COLMAP will discard most of the provided views.

If your COLMAP outputs are OK, then I don't know what could be wrong. Is any mesh generated at all? How long have you trained for? Are you getting good renderings despite bad mesh quality?

That being said, someone produced a similar codebase to this repo ([instant-nsr-pl](https://github.com/bennyguo/instant-nsr-pl)), which seems to have gained a lot of traction. I have tried it and it looks more robust and overall better. That's why for the sake of your time, especially since I have not tried custom data on this codebase, I encourage you to try out that repo and see if it fits your needs.
